---
# Use Ubuntu14.04 Server LTS
sudo: required
dist: trusty

language: python
python: "2.7"

env:
  - SITE=test.yml

before_install:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible==1.9.4

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Install dependencies.
  - git clone https://github.com/ike-jp/ansible-role-anyenv.git ../ike-jp.anyenv
  - ansible-galaxy install yaegashi.blockinfile

script:
  # Uninstall rvm because failed to install Ruby
  # by issuing the following error when run playbook test.
  - rvm implode --force > /dev/null 2>&1

    # Check the role/playbook's syntax.
  - "ansible-playbook -i tests/inventory tests/$SITE --syntax-check"

  # Run the role/playbook with ansible-playbook.
  - "ansible-playbook -i tests/inventory tests/$SITE --connection=local -vvvv"

  # [debug]
  - ruby --version
  - lua -v
  - python -V
  - perl -v
  - ~/ansible_test/local/bin/vim --version

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/$SITE --connection=local -vvvv
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)


