---
- name: Install dependencies
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ vim_dependencies }}"


- name: Clone vim_repository
  git:
    repo: "{{ vim_repository_url }}"
    dest: "{{ vim_temporary_dir_to_build }}"
    version: "{{ vim_installation_version }}"
    force: yes


- name: Make configure
  shell: |
    make clean
    make distclean
    ./configure --prefix={{ vim_installation_dir }} {{ vim_configures_to_build | join(' ') }}
  args:
    chdir: "{{ vim_temporary_dir_to_build }}"


- name: Make
  shell: make
  args:
    chdir: "{{ vim_temporary_dir_to_build }}"


- name: Make install
  shell: make install
  args:
    chdir: "{{ vim_temporary_dir_to_build }}"


