---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"


- include: setup-RedHat.yml
  when: ansible_os_family == "RedHat"


- include: setup-Debian.yml
  when: ansible_os_family == "Debian"


- name: Clone vim_repository
  git:
    repo: "{{ vim_repository_url }}"
    dest: "{{ vim_installation_src_dir }}"
    version: "{{ vim_installation_version }}"
    force: yes


- name: Make configure
  shell: |
    make clean
    make distclean
    ./configure --prefix={{ vim_installation_dir }} {{ vim_configures_to_build | join(' ') }}
  args:
    chdir: "{{ vim_installation_src_dir }}"


- name: Make
  shell: make
  args:
    chdir: "{{ vim_installation_src_dir }}"


- name: Make install
  shell: make install
  args:
    chdir: "{{ vim_installation_src_dir }}"


